language: python

env:
    - PKG=zeroc-ice34

before_install:
    - sudo apt-get -qq update
    - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/anaconda/bin:$PATH
    - conda update --yes conda
    - conda install --yes pip python=2.7

install: ls $PKG

script: true
